# Implement a linear regression model to predict the prices of houses based on their square footage and the number of bedrooms and bathrooms.
https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

In [52]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

In [53]:
data=pd.read_csv("train.csv")
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [54]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [55]:
data.shape

(1460, 81)

In [56]:
data.keys()

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [57]:
relevant_colmns = ['GrLivArea','BedroomAbvGr','FullBath','HalfBath','SalePrice']
data_1 = data[relevant_colmns].dropna()

In [58]:
data_1

      GrLivArea  BedroomAbvGr  FullBath  HalfBath  SalePrice
0          1710             3         2         1     208500
1          1262             3         2         0     181500
2          1786             3         2         1     223500
3          1717             3         1         0     140000
4          2198             4         2         1     250000
...         ...           ...       ...       ...        ...
1455       1647             3         2         1     175000
1456       2073             3         2         0     210000
1457       2340             4         2         0     266500
1458       1078             2         1         0     142125
1459       1256             3         1         1     147500

[1460 rows x 5 columns]

In [59]:
x = data_1[['GrLivArea','BedroomAbvGr','FullBath','HalfBath']]
y = data_1[['SalePrice']]
x

      GrLivArea  BedroomAbvGr  FullBath  HalfBath
0          1710             3         2         1
1          1262             3         2         0
2          1786             3         2         1
3          1717             3         1         0
4          2198             4         2         1
...         ...           ...       ...       ...
1455       1647             3         2         1
1456       2073             3         2         0
1457       2340             4         2         0
1458       1078             2         1         0
1459       1256             3         1         1

[1460 rows x 4 columns]

In [60]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, shuffle=True, random_state=42)

In [61]:
#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()
#x_train_scale = scaler.fit_transform(x_train)
#x_test_scale= scaler.fit_transform(x_test)

In [62]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [63]:
y_pred=model.predict(x_test_scale)
y_pred

C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[ 13807.3590496 ],
       [ 77758.33503901],
       [ 45167.34139695],
       [ 68608.57432429],
       [ 99967.78443369],
       [ 76458.20844792],
       [ 22943.21948125],
       [ 77533.22767704],
       [ 76458.20844792],
       [ 22834.91310898],
       [ 68572.4722002 ],
       [ 13769.9055091 ],
       [ 45141.47142568],
       [ 68583.66965045],
       [ 77578.40359703],
       [ 45163.48020721],
       [ 77584.19538164],
       [ 45187.80570259],
       [ 45164.25244516],
       [ 68572.85831918],
       [ 68635.409593  ],
       [ 77559.09764832],
       [ 77537.08886679],
       [ 45149.57992414],
       [ 68563.59146379],
       [ 99886.50638962],
       [ 68546.02305047],
       [ 45135.67964107],
       [ 77561.80048114],
       [ 99916.04449115],
       [ 13842.88199523],
       [ 77647.13277444],
       [123569.25673533],
       [ 45152.66887593],
       [ 68603.16865865],
       [ 13820.48709472],
       [ 22933.5665069 ],
       [ 46256.64702812],
       [ 15003.23351766],
       [ 45139.15471183],
       [ 13828.20947421],
       [ 77659.48858161],
       [ 13784.57803012],
       [ 77646.36053649],
       [ 13791.91429063],
       [  5978.57535058],
       [ 45144.94649645],
       [ 13785.54332756],
       [ 77695.39764622],
       [ 22860.2039018 ],
       [ 13791.91429063],
       [ 99957.55228088],
       [ 22817.73081463],
       [100214.51445822],
       [ 76500.29541611],
       [ 68622.08848839],
       [ 77594.81365343],
       [ 68504.70832023],
       [ 13816.81896447],
       [ 45128.53644004],
       [ 76436.97190434],
       [ 22806.53336438],
       [ 46361.8644486 ],
       [ 99945.77565216],
       [ 68630.19698685],
       [ 37336.24098409],
       [ 45168.49975388],
       [ 46321.12889682],
       [ 13789.21145781],
       [108901.31852285],
       [ 37215.96492362],
       [ 13834.96655626],
       [ 13776.27647218],
       [ 99855.80993117],
       [109076.23041818],
       [ 45218.11604206],
       [ 77713.93135698],
       [ 77718.95090364],
       [ 13823.18992754],
       [ 45119.46264415],
       [ 54124.23568405],
       [ 45176.80131182],
       [ 45159.61901747],
       [ 45139.92694978],
       [ 22836.26452539],
       [ 13904.85409059],
       [ 77626.47540932],
       [ 54214.20140505],
       [ 76500.29541611],
       [ 77533.22767704],
       [ 45269.85598461],
       [ 46197.18470609],
       [ 45126.41278569],
       [ 46411.48073679],
       [ 37260.94778411],
       [ 68541.38962278],
       [ 77550.98914986],
       [ 77532.4554391 ],
       [ 99944.23117627],
       [ 46338.69731015],
       [ 68607.22290788],
       [ 77593.46223702],
       [ 68716.49457758],
       [ 45133.7490462 ],
       [ 54210.14715582],
       [ 22851.32316539],
       [ 13799.25055114],
       [ 99991.33769112],
       [ 13792.30040961],
       [-30803.05475097],
       [ 76491.02856073],
       [ 68488.10520433],
       [ 22766.76311003],
       [ -8509.6244794 ],
       [ 77599.06096215],
       [ 45124.09607184],
       [ 45142.82284209],
       [ 13769.51939013],
       [ 37286.81775539],
       [ 68601.81724224],
       [ 76484.65759765],
       [ 76500.29541611],
       [ 77561.02824319],
       [ -8444.94955122],
       [ 68559.92333354],
       [ 13781.68213782],
       [ 46319.9705399 ],
       [ 45149.38686465],
       [ 22778.15361977],
       [ 46205.67932353],
       [ 77557.55317242],
       [100046.55270443],
       [ 77595.58589138],
       [-48703.90833954],
       [ 21743.09770448],
       [ 68618.99953659],
       [ 85629.97794417],
       [ 13782.26131628],
       [ 68606.64372942],
       [101403.82490371],
       [ 46423.83654396],
       [ 45148.03544824],
       [ 77586.51209549],
       [ 37246.66138207],
       [ 13805.04233576],
       [ 13774.92505577],
       [ 22963.10460842],
       [ 68563.39840431],
       [ 45117.1459303 ],
       [ 45135.67964107],
       [ 45196.68643899],
       [ 22826.22543206],
       [ 92091.31504136],
       [  5990.93115775],
       [ 13809.09658498],
       [ 55195.20066395],
       [ 71190.62216443],
       [ 45234.33303898],
       [ 45085.67723391],
       [ 13822.03157062],
       [ 68525.55874483],
       [ 53222.00469589],
       [ 68605.09925352],
       [-17471.92443214],
       [ 45203.63658053],
       [-25468.28376597],
       [ 77628.59906368],
       [ 77749.06818363],
       [101124.27476638],
       [ 37383.54055843],
       [ 68662.63098068],
       [ 76506.85943867],
       [ 37213.45515028],
       [ 77552.53362576],
       [ 46438.89518396],
       [ 37226.19707643],
       [ 22853.06070077],
       [ 77583.61620318],
       [ 54196.24687275],
       [ 77555.81563704],
       [ 68531.54358893],
       [ 45170.43034875],
       [ 13785.35026807],
       [ 22834.14087104],
       [ 77636.12838367],
       [ 68617.4550607 ],
       [ 68613.40081147],
       [ 99944.61729524],
       [ 99919.13344294],
       [ 22776.80220336],
       [ 54197.21217018],
       [ 45176.02907387],
       [ 54186.20777942],
       [ 13817.01202396],
       [131274.86848158],
       [123361.13860823],
       [ 85542.13587754],
       [ 13855.43086189],
       [ 77587.8635119 ],
       [ 22825.26013463],
       [ 99950.98825832],
       [ 77531.29708217],
       [ 13860.64346804],
       [ 46392.17478807],
       [ 68545.44387201],
       [ 68476.52163511],
       [ 77642.11322777],
       [ 13817.59120242],
       [ 45276.80612614],
       [ 13773.38057987],
       [ 46317.46076656],
       [ 22814.06268438],
       [ 22802.47911515],
       [ 77536.12356935],
       [ 45232.01632513],
       [ 68589.65449455],
       [  8483.0132769 ],
       [ 13822.03157062],
       [ 13862.18794394],
       [ 37254.38376155],
       [ 13773.76669884],
       [ 99910.63882551],
       [ 68605.29231301],
       [ 22784.33152336],
       [ 68570.34854584],
       [ 13835.73879421],
       [ 45186.64734566],
       [ 37106.50019443],
       [ -8486.65040043],
       [ 45196.30032002],
       [ 45148.42156722],
       [ 77541.91535396],
       [ 45135.67964107],
       [ 13838.44162703],
       [ 77621.84198163],
       [ 13870.68256137],
       [ 99888.243925  ],
       [ 45161.16349337],
       [ 77650.22172623],
       [ 99833.22197118],
       [ 45107.87907492],
       [ 15091.65476275],
       [ 77588.82880933],
       [132506.84507372],
       [ 46246.60793479],
       [ 13861.2226465 ],
       [ 13877.43964342],
       [ 99874.53670142],
       [ 13805.8145737 ],
       [ 45121.20017953],
       [ 46239.27167428],
       [ 77536.31662884],
       [ 13891.72604547],
       [ 45102.2803498 ],
       [ 22789.737189  ],
       [ 99861.4086563 ],
       [ 13837.47632959],
       [ 77503.49651603],
       [ 77561.60742165],
       [ 77655.62739187],
       [ 68668.22970581],
       [ 22799.19710387],
       [ 13773.76669884],
       [ 99972.41786138],
       [ 68620.54401249],
       [ 46257.61232556],
       [ 99913.14859884],
       [ 76500.29541611],
       [ 45162.90102875],
       [ 77528.20813038],
       [109020.62928589],
       [ 99913.14859884],
       [ 77632.65331291],
       [ 22780.66339311],
       [ 99891.3328768 ],
       [ 13794.61712345],
       [ 68617.26200121],
       [100015.85624598],
       [ 76620.95759555],
       [ 22866.76792436],
       [ 77595.00671292],
       [ 76458.20844792],
       [ 77556.3948155 ],
       [ 45121.77935799],
       [ 68618.99953659],
       [ 68574.78891405],
       [ 77607.36252009],
       [ 45187.22652413],
       [ 68582.70435302],
       [ 77533.22767704],
       [-17475.01338393],
       [ 13767.97491423]])

In [64]:
from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'MSE: {mse:.2f}, RMSE: {rmse:.2f}, MAE: {mae:.2f}')
print ("R2 Score:", r2)

MSE: 22047153973.37, RMSE: 148482.84, MAE: 126226.57
R2 Score: -1.8743437212248657

# PREDICTING SALES PRICE FOR NEW HOUSE

In [65]:
new_house = [[2000, 3, 2, 1]]  # [GrLivArea, BedroomAbvGr, FullBath, HalfBath]
predicted_price = model.predict(new_house)
print("Predicted House Price:", predicted_price[0])

Predicted House Price: [242491.45083504]

C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [66]:
new_house = [[1720, 3, 2, 1]]  # [GrLivArea, BedroomAbvGr, FullBath, HalfBath]
predicted_price = model.predict(new_house)
print("Predicted House Price:", predicted_price[0])

Predicted House Price: [214006.33237358]

C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

# INTERPRETATION

#The models performance was evaluated using key metrics. 
#R2 score 0.63, indicating the model explains 78% of the variance in housing prices.
#This metrics highlights that the model captures trends resonably well but could be improved, particulary in reducing error magnitude.

# Usecase example

#For new house with 1720 sq.ft, 3 bedroom, 2 full bath and one half bath the model predicted a price of approximately $214,006, demonstrating it's practical utility.